name = "scan-pwa-api"
main = "index.js"
compatibility_date = "2024-01-01"

# KV Namespace para almacenar sesiones
kv_namespaces = [
  { binding = "SESSIONS", id = "f8cb133155cf40208e997bc9ff157ec1" }
]

# Ruta personalizada (opcional)
[env.production]
route = "api.scanpwa.adservices.work/*"
